---
abstract: 'Shell for Amazon S3'
author:
  - 'Takatoshi Kitano<kitano.t@gmail.com>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.720'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Shell-Amazon-S3
no_index:
  directory:
    - inc
    - t
requires:
  File::HomeDir: 0
  File::Slurp: 0
  Module::Find: 0
  Moose: 0
  Moose::Role: 0
  MooseX::ClassAttribute: 0
  MooseX::Object::Pluggable: 0
  MooseX::Singleton: 0
  Net::Amazon::S3: 0
  Path::Class: 0
  Perl6::Say: 0
  Scalar::Util: 0
  Term::ANSIColor: 0
  Term::ReadLine: 0
  YAML: 0
  namespace::clean: 0
version: 0.04
